# Generated by Django 3.0.4 on 2020-03-11 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Flashcards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=2500)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Flashcards.FlashCard')),
            ],
        ),
    ]
